# City Chain - Continuous Integration Setup for Azure DevOps

trigger:
 batch: true
 branches:
   include:
   - master
   exclude:
   - v* #Exclude verions tags

phases:
- template: build.yml
  parameters:
    name: macOS
    platform: osx
    queue: Hosted macOS

- template: build.yml
  parameters:
    name: Linux
    platform: linux
    queue: Hosted Ubuntu 1604

- template: build.yml
  parameters:
    name: Windows_x86
    platform: win
    arch: x86
    queue: Hosted VS2017

- template: build.yml
  parameters:
    name: Windows_x64
    platform: win
    queue: Hosted VS2017

name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)
