pool:
  vmImage: 'Ubuntu-18.04'

steps:

  - powershell: |
      $version = (Get-Content package.json) -join "`n" | ConvertFrom-Json | Select -ExpandProperty "version"
      Write-Host "##vso[task.setvariable variable=Build.BuildNumber]$version"
      Write-Host "##vso[task.setvariable variable=App.BuildNumber]$version" 
      Write-Host "BUILD_REASON: $Env:BUILD_REASON"
      Write-Host "BUILD_SOURCEBRANCH: $Env:BUILD_SOURCEBRANCH"
      Write-Host "BUILD_SOURCEBRANCHNAME: $Env:BUILD_SOURCEBRANCHNAME"
      Write-Host "SYSTEM_PULLREQUEST_PULLREQUESTID: $Env:SYSTEM_PULLREQUEST_PULLREQUESTID"
      Write-Host "SYSTEM_PULLREQUEST_PULLREQUESTNUMBER: $Env:SYSTEM_PULLREQUEST_PULLREQUESTNUMBER"
      Write-Host "SYSTEM_PULLREQUEST_SOURCEBRANCH: $Env:SYSTEM_PULLREQUEST_SOURCEBRANCH"
    displayName: version number

  - script: docker build -f Docker/$(imageFolder)/Dockerfile -t $(dockerId)/$(imageName) ./Docker/$(imageFolder)/
  - script: |
      docker tag $(dockerId)/$(imageName) latest
      docker tag $(dockerId)/$(imageName) $(dockerId)/$(imageName):$(App.BuildNumber)
  - script: |
      docker login -u $(dockerId) -p $(dockerPassword)
      docker push $(dockerId)/$(imageName)