# City Chain - Continuous Integration Setup for VSTS

#trigger:
#  branches:
#    include:
#    - master
#    - feature/*
#    - bug/*
#    exclude:
#    - v* #Exclude verions tags

phases:
- template: build.yml
  parameters:
    name: macOS
    platform: osx
    queue: Hosted macOS Preview

- template: build.yml
  parameters:
    name: Linux
    platform: linux
    queue: Hosted Linux Preview

- template: build.yml
  parameters:
    name: Windows_x86
    platform: win
    arch: x86
    queue: Hosted VS2017

- template: build.yml
  parameters:
    name: Windows_x64
    platform: win
    queue: Hosted VS2017

name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)
