version: '2'
services:
  nako:
    container_name: city-nako
    restart: always
    networks: 
        nakonet:
            ipv4_address: 172.16.10.100
    image: coinvault/nako-indexer:latest
    command: city
    ports: 
        - 80:9000
        - 443:9000
        - 9019:9000
    depends_on:
        - mongo
        - client
  client:
    container_name: city-client
    restart: always
    networks: 
        nakonet:
            ipv4_address: 172.16.10.101
    image: citychain/citychain
    command: ["-server=1", "-rpcallowip=172.16.10.100", "-rpcbind=172.16.10.101", "-rpcport=5000", "-rpcuser=rpcuser", "-rpcpassword=rpcpassword", "-rpcthreads=300", "-txindex=1"]
    ports: 
        - 5019:5000
        - 4333:4333
  mongo:
    container_name: city-mongo
    restart: always
    networks: 
        nakonet:
            ipv4_address: 172.16.10.102
    image: mongo:3.2
networks:
  nakonet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.10.0/24