version: '2'
services:
  client:
    container_name: city-client
    networks: 
        citynet:
            ipv4_address: 70.28.5.199
    image: citychain/citychain
    command: ["-server=1", "-rpcbind=70.28.5.199", "-rpcallowip=70.28.5.200", "-rpcport=5000", "-rpcuser=rpcuser", "-rpcpassword=rpcpassword", "-rpcthreads=300", "-txindex=1"]
    ports: 
        - 5019:5000
        - 4333:4333
  nako:
    container_name: city-nako
    networks: 
        citynet:
            ipv4_address: 70.28.5.200
    image: majikandy/nako:core
    command: city
    ports: 
        - 9019:9000
    depends_on:
        - mongo
        - client
  mongo:
    container_name: city-mongo
    networks: 
        citynet:
            ipv4_address: 70.28.5.198
    image: mongo:3.2
networks:
  citynet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 70.28.0.0/16